### PR TITLE
Enabling FeaturePeek integration

### PR DESCRIPTION
**Pull request by jasonbarry**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
🎉 Your [FeaturePeek environment](http://peek.run/5m3hg1) is ready for your team to preview!

**Review by jasonbarry — COMMENTED** [review]
oh hi mark  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/xjlhvm#/)

**Review by jasonbarry — COMMENTED** [review]
curious  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/xjlhvm#/)

**Review by jasonbarry — COMMENTED** [review]
foreign object rendering  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/xjlhvm#/)

**Review by jasonbarry — COMMENTED** [review]
processing  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](http://localhost:3000/peek/xjlhvm#/)

**Review by jasonbarry — COMMENTED** [review]
test  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](http://localhost:3000/peek/xjlhvm#/)

**Review by jasonbarry — COMMENTED** [review]
yay  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](http://localhost:3000/peek/xjlhvm#/)

**Review by jasonbarry — COMMENTED** [review]
hi  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](http://localhost:3000/peek/xjlhvm#/)

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). ✌️
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/93phq0**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Pull request closed without merging**
